language: rust
cache: cargo
sudo: false
matrix:
  include:
    - rust: stable
      env:
       - NAME="stable"
       - FEATURES=''
    - rust: nightly
      env:
       - NAME="nightly"
       - FEATURES=''
before_script:
  - |
    LATEST=$(cargo search mdbook | grep "^mdbook =" | cut -d '"' -f 2)
    INSTALLED=$(cargo install --list | grep "^mdbook " | cut -d v -f 2 | tr -d :)
    if [ "$INSTALLED" != "$LATEST" ]; then
      if [ "$INSTALLED" != "" ]; then
        echo "mdbook '$INSTALLED' is already installed"
      fi
      echo "Installing mdbook '$LATEST'"
      cargo install mdbook --force --vers "$LATEST"
    fi
script:
  - mdbook build
  - mdbook test

